name: Continuous Integration (CI)

on:
  push:
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Set up environment
        run: |
          export GRADLE_USER_HOME=$HOME/.gradle
          export SPRING_PROFILES_ACTIVE=test

      - name: Test with Gradle
        run: |
          gradle check --info --stacktrace
          gradle test
          gradle jacocoTestReport

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/test-results